config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



    resources :tours do 
      resources :sites
    end


get "stay", to: "house#stay"


    root "tours#index"

    get "/discover", to: "discover#ghana"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord

    belongs_to :tour
end

app/models/tour.rb
class Tour < ApplicationRecord
  
    validates :name, presence: true
    validates :price, presence: true
    validates :description, presence: true
    has_one_attached :image

    belongs_to :user

    has_many :sites, dependent: :destroy
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :tours
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
    def ghana
    end
end

app/controllers/house_controller.rb
class HouseController < ApplicationController
    def stay
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tour, only: %i[create edit update destroy]

    def create   
        @site = @tour.sites.create(site_params)

        if @site.save
            redirect_to @tour
        end
    end

    def edit 
        @site = @tour.sites.find(params[:id])
    end

    def update
        @site = @tour.sites.find(params[:id])
        @site.update(site_params)
        redirect_to @tour
    end

    def destroy
        @site = @tour.sites.find(params[:id])
        @site.destroy   
        redirect_to @tour
    end

    private

    def set_tour
        @tour = Tour.find(params[:tour_id])
    end

    def site_params
        params.require(:site).permit(:name, :description)
    end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_tour, only: %i[show edit destroy update]  

    def index
        @tours = Tour.all
    end

    def new
        @tour = current_user.tours.build
    end

    def create
        @tour = current_user.tours.build(tour_params)
        if @tour.save
            redirect_to tours_path, notice: "Tour saved successufully" 
        else
            render :new
        end
    end

    def show 
    end

    def edit 
    end 

    def update
        @tour.update(tour_params)
        redirect_to @tour, notice: "Tour updated sucessfully"
    end

    def destroy
        @tour.destroy
        redirect_to root_path, notice: "Tour deleted successfully"
    end

    private

    def set_tour 
        @tour = Tour.find(params[:id])
    end
  
    def tour_params
        params.require(:tour).permit(:name, :price, :duration, :accommodation, :meals, :entry_tickets, :pick_up, :transport, :description, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/helpers/house_helper.rb
module HouseHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/discover/ghana.html.erb
<section style="margin-top: 90px">
    <div id="find-team" class="find">
        <%= image_tag "colors.png", alt: "colors" %>
        <p class="adventure">Our favourite things to do in Ghana</p>
    </div> 
</section>

<div class="shai">

    <div class="things-todo-wrapper">
        <div id="first-todo-pic"class="todo-pic">
            <%= image_tag "boti-forest.png", alt: "boti-forest", class: "todo-image"%>
        </div>
    
        <div id="first-todo-text" class="todo-info-wrapper"> 
            <div class="todo-info-text">
                <h1 class="todo-heading">Take a stroll <br> in the  rain forest</h1>
                <p>Just outside Accra, Ghana is home to vast protected rain forestes and natural reserves. Walking through the jungle you can discover endless hidden gems, from uniquely shaped rocks to fresh streams, and finally take a shower under a waterfall.</p>    
            </div>
            <%= image_tag"red_triangle", class: "todo-triangle" %> 
        </div>

       
        <div id="second-todo-pic" class="todo-pic">
            <%= image_tag "oasis-beach", alt: "robi-sea", class: "todo-image" %>
        </div>
    
        <div id="second-todo-info-wrapper"class="todo-info-wrapper">
            <%= image_tag"right_yellow_triangle", class: "todo-triangle" %> 
            <div class="todo-info-text">
                <h1 class="todo-heading">Watch the ocean <br> waves crash</h1>
                <p>If you want to have a break from the hot sun there is nothing more refreshing than sitting by the ocean and watch the waves crash. If you are lucky you might catch little turtles ashore making their journey back to the sea. </p>       
            </div>  
        </div>
    
        <div id="third-todo-pic" class="todo-pic">
            <%= image_tag "sobolodrink", alt: "sobolo-drink", class: "todo-image" %>
        </div>
    
        <div class="todo-info-wrapper">   
            <div class="todo-info-text">
                <h1 class="todo-heading">Lift the spirit with <br>local drinks</h1>
                <p>Ghanaians have a strong drinking culture, that’s why we have many original recipees to suit every taste, like Sobolo, made from hibiscus, Palm wine, made from palm tree, and Akpeteshie, made from sugar cane. </p>
            </div>  
            <%= image_tag"green_triangle.png", class: "todo-triangle" %> 
        </div>
    
        <div id="fourth-todo-pic" class="todo-pic">
            <%= image_tag "robi-fufu", alt: "robi-fufu", class: "todo-image"%>
        </div>
      
        <div class="todo-info-wrapper">
            <%= image_tag"right_yellow_triangle", class: "todo-triangle" %>   
            <div class="todo-info-text">
                <h1 class="todo-heading">Get your fingers dirty</h1>
                <p>Most Ghanaian dishes are best eaten with hands (even rice!). You can’t miss Fufu, a hot soup with your choice of meat or fish with a soft dough ball, Jollof rice with fried chicken and fresh Tilapia fish.</p>
            </div>  
        </div>
    
        <div id="third-todo-pic" class="todo-pic">
            <%= image_tag "makola", alt: "makola", class: "todo-image"%>
        </div>
      
        <div class="todo-info-wrapper">
            <div class="todo-info-text">
                <h1 class="todo-heading">Get the best deals <br> the local market</h1>
                <p>If you want to buy the freshest ingredients, hand-crafted souvenirs or natural skin products, like black soap and shea butter, head to Makola Market in Accra. We will help you getting the best deals and teach you some bargaining tricks.</p>
            </div>  
            <%= image_tag"red_triangle", class: "todo-triangle" %> 
        </div>

        <div id="second-todo-pic" class="todo-pic">
            <%= image_tag "beads", alt: "beads", class: "todo-image" %>
        </div>
    
        <div id="second-todo-info-wrapper"class="todo-info-wrapper">
            <%= image_tag"right_yellow_triangle", class: "todo-triangle" %> 
            <div class="todo-info-text">
                <h1 class="todo-heading">Mix and match <br>traditional beads</h1>
                <p>Ghanaian women love making original necklaces and earrings with colourful beads and stones. On the street you can buy long strings of beads that can be adjusted to fit your waist and feet.</p>       
            </div>  
        </div>

        <div id="first-todo-pic"class="todo-pic">
            <%= image_tag "chilling.png", alt: "Outdoor parties", class: "todo-image"%>
        </div>
    
        <div id="first-todo-text" class="todo-info-wrapper"> 
            <div class="todo-info-text">
                <h1 class="todo-heading">Dance the night away</h1>
                <p>Music is an essential part of every-day life in Ghana and everyone, from children to elderly people, enjoy and are good at dancing. At night you will be able to choose from rooftop bars, live concerts and open-air bars.</p>    
            </div>
            <%= image_tag"green_triangle.png", class: "todo-triangle" %> 
        </div>
    </div>

</div>

app/views/house/stay.html.erb
<div class="house-wrapper">
    <div class="stay-wrapper">

        <%= image_tag "voltahouse", class: "volta-house" %>
        <div class="volta-house-info">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque distinctio error, quas similique eligendi perspiciatis! Eos corporis fugit ipsa? Eveniet, laboriosam? Itaque iusto, similique eaque excepturi ut aspernatur! Sit, numquam.
        </div>

        <%= image_tag "kokrobite", class: "kokrobite-house" %>
        <div class="kokrobite-house-info">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque distinctio error, quas similique eligendi perspiciatis! Eos corporis fugit ipsa? Eveniet, laboriosam? Itaque iusto, similique eaque excepturi ut aspernatur! Sit, numquam.
        </div>
        
        <%= image_tag "oasis-dog", class: "oasis-house" %>
        <div class="oasis-house-info">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque distinctio error, quas similique eligendi perspiciatis! Eos corporis fugit ipsa? Eveniet, laboriosam? Itaque iusto, similique eaque excepturi ut aspernatur! Sit, numquam.
        </div>
        
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
    
  <div class="socail-wrapper">
    <div class="footer-contacts">

      <p class="contactus">Contact us:</p>

      <div class="footer-icons">
       <%= image_tag "camera", class: "footer-social", alt: "footer-social"  %>
       <p>ghana_sobolotours</p>
      </div>

      <div class="footer-icons">
        <%= image_tag "call", class: "footer-social", alt: "footer-social"  %> 
        <p>+233 547 917539</p>  
      </div> 

      <div class="footer-icons">
        <%= image_tag "send", class: "footer-social", alt: "footer-social"  %>
        <p>ghanasobolotours@gmail.com</p>
      </div>
    </div>

    <div  id="footer-pic" class="footer-pic"> 
      <%= image_tag("footerlogo.png", class: "footer-logo", alt: "logo" ) %>
    </div>
    
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="nav-wrapper" >
  <div class="nav-items">

    <div class="logo-burger-wrapper">
      <%= link_to image_tag("sobolo.png", class: "logo", alt: "logo"), root_path %>
    </div>

    <div class="nav-links" data-controller="nav-hover" data-action="click->nav-hover#shai">
      <%= link_to "Home", tours_path, class:"nav-link", data: {}    %>
      <%= link_to "Discover Ghana", discover_path, class:"nav-link", data: {} %>
      <%= link_to "Accommodation", stay_path, class:"nav-link", data: {} %>
        
      <% if user_signed_in? && current_user.admin? %> 
       <%= link_to "new tour", new_tour_path %>      
      <% end %>

      <% if user_signed_in? %>
        <%= link_to "sign out", destroy_user_session_path, method: :delete, class:"sign-out" %>
      <% else %>
        <%= link_to "sign up", new_user_registration_path, class: "sign-up" %>
        <%= link_to "login", new_user_session_path, class:"login" %>
      <% end %>
    </div>

    <div id="burger-wrapper" class="burger-wrapper" data-controller="side-nav" data-action="click->side-nav#openNav">
      <div class="burger"></div>
      <div class="burger"></div>
      <div class="burger"></div>
    </div>

  </div>
</nav>

app/views/layouts/_notification.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_side_nav.html.erb
<div id="side-nav" class="side-nav-wrapper">

  <div  id="close" class="close" data-controller="side-nav" data-action="click->side-nav#closeNav">
  </div>

  <div id="side-links" class="side-links">

    <div class="side-link">
      <%= link_to "Home", root_path %>
    </div>

    <div class="side-link">
      <%= link_to "Tours", tours_path %>
    </div>

    <div class="side-link">
      <%= link_to "Discover Ghana", discover_path %>
    </div>

    <div class="side-link">
      <%= link_to "Accommodation", stay_path %>
    </div>

    <div class="side-link">
        <% if user_signed_in? %>
          <%= link_to "sign out", destroy_user_session_path, method: :delete, class:"sign-out" %>
        <% else %>
          <%= link_to "sign up", new_user_registration_path %>
         <p style="margin-top: 20px;"><%= link_to "login", new_user_session_path %></p>
        <% end %>
    </div>
    
    <div class="side-link">
      <% if user_signed_in? && current_user.admin? %> 
       <%= link_to "new tour", new_tour_path %>      
      <% end %>
    </div>
      
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ghana Sobolo Tours</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,900;1,400;1,500&display=swap" rel="stylesheet">
  </head>
  
  <body>
    <div id="ster" class="ster">

      <%= render "layouts/notification" %>
      <%= render "layouts/nav" %>

      <%= yield %>

      <%= render "layouts/footer" %>

    </div>

    <%= render "layouts/side_nav" %>
    
  </body>
</html>
    

app/views/sites/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="site-edit-form-wrapper">
    <%= form_with model: [@tour, @site] do |form| %>
        
    
        <p><%= form.label :name %></p>
        <%= form.text_field :name %>
    
        <p><%= form.label :description %></p>
        <%= form.text_area :description %>
    
        <div>
            <%= form.submit "Add site", class: "add-site-btn" %>
        </div>
    
    <% end %>

</div>



<%= link_to "Back", tour_path(@tour) %>

app/views/tours/_accra.html.erb
<% if @tour.name == "Accra" %>
    <div class="itinerary">
        <div class="itinerary-wrapper">

            <div class="tour-map-wrapper">
                <%= image_tag "accra-map", class: "tour-map" %>
            </div>

            <div class="itinerary-details">
                <% @tour.sites.each do |site| %>
                    <div class="itinerary-text">
                        <h1><%= site.id %></h1>
                        <h1><%= site.name %></h1>

                    <% if user_signed_in? && current_user.admin? %> 
                        <p style="margin-left:10px;"><%= link_to "edit", edit_tour_site_path(@tour, site) %> </p>
                        <p style="margin-left:10px;"><%= link_to "delete", [@tour, site], method: :delete, data: { confirm: "are you sure?"} %></p> </p>
                    <% end %>

                        <p style="width: 100%;"><%= site.description %></p>
                    </div>
                <% end %>
            </div>
        </div>  
        

        <div class="site-pics-wrapper">

            <div class="site-pics">
                <%= image_tag "james-town", class:"site-pic" %>
                <%= image_tag "art-center", class:"site-pic" %>
                <%= image_tag "square", class:"site-pic" %>
                <%= image_tag "nkrumah", class:"site-pic" %>
            </div>
        </div>
        

    </div>    
<% end %>

app/views/tours/_cape.html.erb
<% if @tour.name == "Cape coast" %>
    <div class="itinerary">
        <div class="itinerary-wrapper">

            <div class="tour-map-wrapper">
                <%= image_tag "cape-map", class: "tour-map" %>
            </div>

            <div class="itinerary-details">
                <% @tour.sites.each do |site| %>
                    <div class="itinerary-text">
                        <h1><%= site.id %></h1>
                        <h1><%= site.name %></h1>
                        
                    <% if user_signed_in? && current_user.admin? %> 
                        <p style="margin-left:10px;"><%= link_to "edit", edit_tour_site_path(@tour, site) %> </p>
                        <p style="margin-left:10px;"><%= link_to "delete", [@tour, site], method: :delete, data: { confirm: "are you sure?"} %></p> </p>
                    <% end %>

                        <p style="width: 100%;"><%= site.description %></p>

                    </div>
                <% end %>
            </div>
        </div>  
        
        <div class="site-pics-wrapper">
            <div class="site-pics">
                <%= image_tag "kakum-walk", class:"site-pic" %>
                <%= image_tag "cape-coast-castle", class:"site-pic" %>
                <%= image_tag "tuk-tuk", class:"site-pic" %>
                <%= image_tag "pigs", class:"site-pic" %>
            </div>
        </div>

    </div>    
<% end %>

app/views/tours/_eastern.html.erb
<% if @tour.name == "Eastern"%>
    <div class="itinerary">
        <div class="itinerary-wrapper">

            <div class="tour-map-wrapper">
                <%= image_tag "eastern-map", class: "tour-map" %>
            </div>

            <div class="itinerary-details">
                <% @tour.sites.each do |site| %>
                    <div class="itinerary-text">
                        <h1><%= site.id %></h1>
                        <h1><%= site.name %></h1>

                    <% if user_signed_in? && current_user.admin? %> 
                        <p style="margin-left:10px;"><%= link_to "edit", edit_tour_site_path(@tour, site) %> </p>
                        <p style="margin-left:10px;"><%= link_to "delete", [@tour, site], method: :delete, data: { confirm: "are you sure?"} %></p> </p>
                    <% end %>
                    
                        <p style="width: 100%;"><%= site.description %></p>
                    </div>
                <% end %>
            </div>
        </div>  
        
        <div class="site-pics-wrapper">
            <div class="site-pics">
                <%#= image_tag "kakum-walk", class:"site-pic" %>
                <%#= image_tag "cape-coast-castle", class:"site-pic" %>
                <%#= image_tag "tuk-tuk", class:"site-pic" %>
                <%#= image_tag "pigs", class:"site-pic" %>
            </div>
        </div>

    </div>    
<% end %>

app/views/tours/_site_form.html.erb
<div class="site-form-wrapper">
    <%= form_with model: [@tour, @tour.sites.build] do |form| %>
        <p><%= form.label :name %></p>
        <%= form.text_field :name %>

        <p><%= form.label :description %></p>
        <%= form.text_area :description %>

        <div>
            <%= form.submit "add Site", class: "tour-btn" %>
        </div>
    <% end %>
</div>

app/views/tours/_sites.html.erb
<div class="sites-wrapper">
    <% @tour.sites.each do |site| %>
        <div class="show-site">
            <%= site.name %>
            <%= link_to "edit", edit_tour_site_path(@tour, site) %> 
            <%= link_to "delete", [@tour, site], method: :delete, data: { confirm: "are you sure?"} %></p> 
        </div>
    <% end %>
</div>

app/views/tours/_volta.html.erb
<div class="itinerary">
    <% if @tour.name == "volta" %>
        <div class="itinerary-wrapper">
            <div class="tour-map-wrapper">
                <%= image_tag "voltamap", id: "how-it-works", class: "tour-map"  %>
            </div>
    
            <div class="itinerary-details">
                <% @tour.sites.each do |site| %>
                    <div class="itinerary-text">
                        <h1><%= site.id %></h1>
                        <h1><%= site.name %></h1>
                        
                        <% if user_signed_in? && current_user.admin? %> 
                            <p style="margin-left:10px;"><%= link_to "edit", edit_tour_site_path(@tour, site) %> </p>
                            <p style="margin-left:10px;"><%= link_to "delete", [@tour, site], method: :delete, data: { confirm: "are you sure?"} %></p> </p>
                        <% end %>

                        <p style="width: 100%;"><%= site.description %></p>
                    </div>
                <% end %>
            </div>
        </div>


        <div class="site-pics-wrapper">
            <div class="site-pics">
                <%= image_tag "wlifalls", class:"site-pic" %>
                <%= image_tag "cuddle-monkey", class:"site-pic" %>
                <%= image_tag "monkey-king", class:"site-pic" %>
                <%= image_tag "ferry", class:"site-pic" %>
            </div>
        </div>
    <% end %>
</div>    

app/views/tours/edit.html.erb
<%= render "form" %>

app/views/tours/index.html.erb
<div class="hero-container" data-controller="hero">
    <div class="hero-background" data-hero-target="background"></div>
    <div class="hero-text" data-action="mouseover->hero#mouse mouseout->hero#out">
        <h1 class="discover-text">Discover Ghana <br/> with the locals</h1> 
        <button class="hero-text-btn"><a href="#find-tours">view tours</a></button>
        <button id="discover-ghana-btn" class="hero-text-btn"><%= link_to "discover Ghana", discover_path %></button>
    </div> 
</div>


<div id="tour-offer-wrapper">
    <div id="tour-offer" class="tour-offer" >
        <div class="sustainable-icons">
            <%= image_tag("loco2.png") %>
            <h5>Made by locals</h5>
        </div>
    
        <div class="sustainable-icons">
            <%= image_tag("leaf.png") %>
            <h5>Eco friendly</h5>
        </div>
    
        <div class="sustainable-icons">
            <%= image_tag("fares.png") %>
            <h5>Transparent fares</h5>
        </div>
    
        <div class="sustainable-icons">
            <%= image_tag("loco.png") %>
            <h5>Tailored itineraries</h5>
        </div>
    </div>
</div>


<section data-controller="show">
    <div id="find-tours" class="find" data-action="scroll@window->show#showHeadings">
        <%= image_tag "colors.png", alt: "colors" %>
        <p class="adventure">Find your next adventure </p>
        <p class="adventure-text">Our tours are designed for small groups of 4-5 people, so that we can keep them flexible and tailor them for you along the way. </p>
        <p class="adventure-text"> From the pick-up at your accomodation we will take care of every aspect of the tour, so you don’t need to carry a cent with you.</p>
    </div> 
</section>

<div class="tour-container" data-controller="tour-card" data-action="mouseenter->tour-card#mouse">
    <% @tours.each do |tour| %>
        <div class="tour-card" data-tour-card-target="card">
            
            <%= link_to image_tag(tour.image), tour_path(tour) %>

            <div class="" id="tour-name">
                <p class="tour-name"><%= tour.name.capitalize %></p>
            </div>

            <div class="index-sites">
                <% tour.sites.each do |site| %>
                        <%= site.name %> 
                <% end %>
            </div>

            <div id="read-more">
                <%= link_to "read more ", tour_path(tour), class: "read-more" %>
            </div>
                            
            <div class="tour-card-item", id="tour-price">
                <p><%= number_to_currency(tour.price, unit: "€" ) %></p>    
            </div> 

        </div>
    <% end %>
</div>


<section data-controller="show">
    <div id="find-team" class="find" data-target="find">
        <%= image_tag "colors.png", alt: "colors" %>
        <p class="adventure">Meet our team </p>
        <p class="adventure-text">Our tours are designed for small groups of 4-5 people, so that we can keep them flexible and tailor them for you along the way. </p>
        <p class="adventure-text">From the pick-up at your accomodation we will take care of every aspect of the tour, so you don’t need to carry a cent with you.</p>
    </div> 
</section>



<section class="team-back">
    <div class="team-wrapper">
        <div class="team">
            <%= image_tag"janet" %>
            <p class="team-name">Janet</p>
            <div class="team-info">
                <p>
                     Born and raised in downtown Accra, Janet is a caterer by profession who enjoys teaching visitors authentic Ghanaian recipes. When she is not  not managing events, she loves dancing and having parties at the beach.  She has the best tips if you want to discover the best food joints and shops in Accra.</p>
            </div>
        </div>

        <div class="team">
            <%= image_tag"edem.jpeg" %>
            <p class="team-name">Edem</p>
            <div class="team-info">
                <p>
                     Originally from a village by the Volta lake and residing in Accra, Edem is the main point of contact for the Sobolo tours. He is a patient driver and enjoys hiking in the rain forests and mountains of Volta.  Let him know if you want to get the coolest sneakers in town.</p>
            </div>
        </div>
        
        <div class="team">
            <%= image_tag"amount.jpeg" %>
            <p class="team-name">Amount<p>
            <div class="team-info">
            <p>
                 Nana Kwame, aka Skoda, is originally from Cape Coast but lived all his life in Accra. When he is not working as a lab technician, he enjoys spending time at the beach and showing visitors hidden treks in the wild. He is the go-to person if you want to know the best spots to dance in Accra.
            </p>            
        </div>
        </div>
    </div>
</section>

<section data-controller="show">
    <div id="find-tours" class="find" >
        <%= image_tag "colors.png", alt: "colors" %>
        <p class="adventure">Discover Ghana</p>
        <p style="margin-top: 10px;">Stretching from the atlantic ocean to the savannah in the north, Ghana has incredibly diverse natural treasures like peaceful beaches by the ocean,  luscious rain forests, monkey sanctuaries, waterfalls and safari reserves. </p>
        <p style="margin-top: 10px;"> Together with its vibrant culture and heritage, welcoming atmoshpere and rich cuisine, Ghana is the perfect destination  if you are looking for adventure, fun and untouched nature.</p>
    </div> 
</section>


<div class="tour-discover-wrapper">
    <div class="tour-discover">
        <div class="discover-image">
            <%= image_tag"robiwalk" %>
            <%= image_tag "veggies" %>
            <%= image_tag "ele" %>
            <%= image_tag "beads" %>
        </div>
        
        <div class="discover-info">
            <div class="discover-heading-button">
                <h1 class="todo-heading">Our favourite things to do in Ghana </h1>
                <button style="padding: 10px; background: rgb(25, 157, 197); border: none; color: white; font-size: 1.5em;">click me</button>            
            </div>
            <%= image_tag "green_triangle", class: "todo-triangle" %>
        </div>
    </div>
</div>

app/views/tours/new.html.erb
<%= render "form" %>

app/views/tours/show.html.erb
<div class="tour-show-wrapper">
    <div class="tour-show">

        <% if @tour.image.persisted? %>
            <div class="tour-pic">
                <%= image_tag(@tour.image) %>
            </div>
        <% end %>
        
        <div id="show-tour-description" class="show-tour-description">
            <p class="tour-region"><%= @tour.name.capitalize %> Experience</p>

            <div class="description-text">
                <%= @tour.description %>
            </div>
    
            <% if user_signed_in? && @tour.user_id == current_user.id %> 
                <div class="tour-show-btn-wrapper">
                    <%= link_to "edit", edit_tour_path(@tour), class: "edit-btn" %>
                    <%= link_to "delete", tour_path(@tour), method: :delete, data: { confirm: "are you sure?"}, class:"delete-btn" %>
                </div>  
            <% end%>
        </div>
        
        <div class="show-tour-details">
            <div class="show-tour-detail">
               <p style="color: #F47559; font-weight: 500; font-size: 2.2em;"><%= number_to_currency(@tour.price, unit: "€" )  %></p>  
               <p style="margin-left: 5px; font-size: 0.8em;">per person</p>
            </div>
    
            <div class="show-tour-detail">
               <p>
                   <%= @tour.duration > 1 ? "#{@tour.duration}  days trip" : " 1 day trip" %>
               </p>
            </div>
            
            <% if  @tour.meals? %>
                <div class="show-tour-detail">
                    <%= image_tag("soup") %>
                    <p>Meal</p>   
                </div>
            <% end %>
            
            <% if  @tour.entry_tickets? %>
                <div class="show-tour-detail">
                    <%= image_tag("ticket") %>
                    <p>Tickets</p>   
                </div>
            <% end %>
            
            <% if  @tour.accommodation? %>
                <div class="show-tour-detail">
                    <%= image_tag("bed") %>
                    <p>Accommodation</p>   
                </div>
            <% end %>
            
            <% if  @tour.pick_up? %>
                <div class="show-tour-detail">
                    <%= image_tag("pickup") %>
                    <p>Pickup</p>   
                </div>
            <% end %>
            
            <% if  @tour.transport? %>
                <div class="show-tour-detail">
                    <%= image_tag("bus") %>
                    <p>Transport</p>   
                </div>  
            <% end %>
        </div> 
        
        
        <div class="bookings-wrapper">

            <%= link_to "Reserve" %>

        </div>
    </div>    

</div>

<section>
    <div id="find-tours" class="find">
        <%= image_tag "colors.png", alt: "colors" %>
        <p class="adventure"><%= @tour.name %> itinerary </p> 
    </div> 
</section>

<%= render "volta" %>
<%= render "accra" %>
<%= render "eastern" %>
<%= render "cape" %>
        
<% if user_signed_in? && current_user.admin? %> 
    <%= render "tours/site_form" %>
<% end%>